#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pagure"
name = "Pagure"
description.en = "A git-centered forge, python based using pygit2."

version = "5.13.3~ynh3"

maintainers = ["Jean-Baptiste Holcroft"]

[upstream]
license = "AGPL-3.0"
website = "https://pagure.io/pagure"
demo = "https://pagure.io"
admindoc = "https://docs.pagure.org/pagure/"
code = "https://pagure.io/pagure"
cpe = "cpe:2.3:a:redhat:pagure"

[integration]
yunohost = ">= 11.2.12"
architectures = "all"
multi_instance = false
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pagure"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    url = "https://releases.pagure.org/pagure/pagure-5.13.3.tar.gz"
    sha256 = "f684d8193d4c4cf637b465c80cbfece6eb2b1646df3ec4f993adf75ea78d5a1a"


    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["repos", "remotes", "attachments", "releases"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "gcc",
        "git",
        "libffi-dev",
        "libgit2-dev",
        "libjpeg-dev",
        "libpq-dev",
        "python3-cffi",
        "python3-dev",
        "python3-gdbm",
        "python3-psycopg2",
        "python3-venv",
        "python3",
        "redis-server",
        "uwsgi-plugin-python3",
        "uwsgi",
        "virtualenv",

        "postgresql",
    ]

    [resources.database]
    type = "postgresql"
