#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_redis
source ynh_uwsgi_service__2
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

services=(
    "${app}_authorized_keys_worker"
    "${app}_ci"
    "${app}_ev_server"
    "${app}_gitolite_worker"
    "${app}_loadjson"
    "${app}_logcom"
    "${app}_milters"
    "${app}_mirror"
    "${app}_webhook"
    "${app}_worker"
)
for service in "${services[@]}"; do
    if ynh_exec_warn_less yunohost service status "$service" >/dev/null; then
        yunohost service remove "$service"
    fi
    ynh_remove_systemd_config --service="$service"
done

ynh_remove_uwsgi_service --service="$app"

# Remove the dedicated NGINX config
ynh_remove_nginx_config

ynh_redis_remove_db "$redis_db"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed"
